services:
  accounts:
    image: "quannguyen1999/accounts:s1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - quannguyen1999
  loans:
    image: "quannguyen1999/loans:s1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - quannguyen1999
  cards:
    image: "quannguyen1999/cards:s1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - quannguyen1999
networks:
  quannguyen1999:
    driver: "bridge"