build:
  version: "2.0"
accounts:
  message: "Welcome to quan accounts related Prod APIs"
  contactDetails:
    name: "quan Ray - prod Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - 0708821228