build:
  version: "3.0"

accounts:
  message: "Welcome to quan accounts related Local APIs"
  contactDetails:
    name: "quan Ray - local Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - 0708821228